admin_controllers:
    resource: ../../src/AdminBundle/Controller/
    type: annotation
    prefix: /admin

api_controllers:
    resource: ../../src/ApiBundle/Controller/
    type: annotation
    prefix: /api